version: '3.9'
services:
  sql_server:
    container_name: sasserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "9876:1433"
    volumes:
      - sas-db-volume:/var/lib/mssql/data
    env_file:
      - sasserver/sasserver.env

  dev-env:
    container_name: sas-dev
    build:
      context: ./sas-dev
    volumes:
      - "..:/workspace"
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    x-develop:
      watch:
        target: ..
        volume: /workspace

volumes:
  sas-db-volume: null